Maxine
nakanu18/react-minigames pull request #3
Opened 2021-07-07 16:56 UTC by maxcausevic

oops

2021-07-07 17:05 UTC, nakanu18 requested changes

2021-07-07 17:05 UTC, nakanu18 commented on public/index.html
> +        />
so i will say i'm not familiar with web dev but lets not go this route.  we can just use some css we build.  so go ahead and delete this line

2021-07-07 17:05 UTC, nakanu18 commented on src/App.js
> +            <div className="container bg-secondary mt-4">
delete this for now

2021-07-07 17:05 UTC, nakanu18 commented on src/TicTacToe/TicTacToe.js
> +                <h1 className="text-center">Tic Tac Toe</h1>
instead of using text-center, let's create some css for this.  so change this line back to 
```
className={styles.header}
```

go into styles.module.css and you'll find the header1

here you should find how to do text-align: center
https://www.w3schools.com/cssref/pr_text_text-align.ASP

2021-07-07 17:05 UTC, nakanu18 commented on src/TicTacToe/TicTacToe.js
> +            <div className="container">
remove   the className for now

2021-07-08 03:07 UTC, maxcausevic commented on public/index.html
> +        />
I can't use bootstrap?!

2021-07-08 04:07 UTC, nakanu18 commented on public/index.html
> +        />
lets not use it for now.  i wanna build up the css so we can manually do it

2021-07-09 01:48 UTC, nakanu18 approved these changes

2021-07-09 01:48 UTC, merged

2021-07-26 18:06 UTC, maxcausevic commented
Need help with props and state.